.\" Hey, EMACS: -*- nroff -*-
.TH MEMBERSYS "1" "Nov 2013" "membersys"
.SH NAME
membersys \- Starship Factory membership management system
.SH SYNOPSIS
.TP
.B membersys
[\fI--bind="HOST"|--bind="HOST:PORT"\fR]
[\fI--lockserver-boot-uri=DOOZER_URI\fR]
[\fI--lockserver-uri=DOOZER_URI\fR]
[\fI--service-name=STRING\fR]
\fI--template-dir=/path/to/templates\fR
.SH DESCRIPTION
.PP
.B membersys
is a web based membership management system. It allows new members to apply
for membership in an organization and will later give the organization
members a means to approve the requests.
.SH OPTIONS
.TP
\fB\-\-bind=HOST|\-\-bind=HOST:PORT\fR
tells
.B membersys
to listen to the given host (in doozer exported anonymous ports) or host:port
pair.
If the
.I \-\-lockserv
flag is not empty,
.B membersys
will bind to an anonymous port on the given host and export the host:port pair
to a Doozer lockservice.
.TP
\fB\-\-lockservice\-uri=\fR
.TP
\fB\-\-lockservice\-boot\-uri=\fR
are used to tell
.B membersys
to use an exported anonymous port and publish its presence to the Doozer
lockservice given.
uri and boot\-uri will be normal Doozer service URIs and will be used as in
any other Doozer client.
See
.IR doozer (1)
for more details.
.TP
\fB\-\-service-name\fR=STRING
tells
.B membersys
what service name to publish under to the Doozer service.
.TP
\fB\-\-template-dir\fR=STRING
indicates to
.B membersys
where to find the HTML templates to serve.
The directory this points at must at least contain the files
.I form.html
and
.IR printlayout.html .
Any files in the directories
.I js
and
.I css
in those directories will be served as-is.
.SH SECURITY
.PP
.B membersys
does not serve any files outside of the directory given as
.IR \-\-template\-dir ,
so you just need to be careful not to put anything into
.I js
and
.I css
which you don't want to see public.
.PP
Apart from binding to a port and reading the template files, no special
privileges are required. It is recommended to bind
.B membersys
to an anonymous port or one above 1024 and run it as an unprivileged user.
.SH EXAMPLES
A command line like
.IP
membersys \-\-template\-dir=/usr/local/share/membersys \-\-bind=192.0.2.1:8080
.PP
will run
.B membersys
listening to port 8080 at the IP address 192.0.2.1, using a fixed port, and
serving templates from /usr/local/share/membersys.
.PP
On the other hand, something like
.IP
membersys \-\-template\-dir=/usr/local/share/membersys \-\-bind=192.0.2.2
\-\-lockserver-boot-uri=doozer:?ca=192.0.2.3:8046
\-\-lockserver-uri=doozer:?cn=foobar
\-\-service\-name=membersys
.PP
will run
.B membersys
listening to an anonymous port on IP 192.0.2.2, serving files from
/usr/local/share/membersys, binding to Doozer server 192.0.2.3 and exporting
to the Doozer named cluster foobar as service membersys.
.SH FILES
.B membersys
uses the template files in
.IR \-\-template\-dir .
No other files are used.
.SH AUTHOR
Written by Tonnerre Lombard.
.SH "REPORTING BUGS"
Please report bugs via e-mail at
.I open\-at\-lists.starship-factory.ch
or file them via ditz and send a pull request to
.IR https://github.com/starshipfactory/membersys .
.PP
Please visit
.I http://bugs.starship-factory.ch/membersys/
for an overview of the current state of bug squashing.
.SH COPYRIGHT
.PP
Copyright \(co 2013 Tonnerre Lombard, Starship Factory. All Rights Reserved.
.PP
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the conditions outlined in the
3-Clause BSD license are met.
