--- !ditz.rubyforge.org,2008-03-06/project 
name: membersys
version: "0.1"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: membersys
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.1"
  status: :released
  release_time: 2013-12-02 01:56:32.807880 Z
  log_events: 
  - - 2013-11-15 16:31:20.483725 Z
    - Caoimhe Chaos <caoimhechaos@protonmail.com>
    - created
    - Proof of Concept release featuring just the web interface
  - - 2013-12-02 01:56:32.807890 Z
    - Caoimhe Chaos <caoimhechaos@protonmail.com>
    - released
    - With no bugs left and none reported, it seems time to release version 0.1.
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.2"
  status: :released
  release_time: 2014-02-09 04:19:25.832198 Z
  log_events: 
  - - 2014-02-09 04:59:50.263568 Z
    - Caoimhe Chaos <caoimhechaos@protonmail.com>
    - created
    - Split yearly/monthly payment and logo.
  - - 2014-02-09 04:19:25.832209 Z
    - Caoimhe Chaos <caoimhechaos@protonmail.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.3"
  status: :released
  release_time: 2014-09-02 20:52:33.645361 Z
  log_events: 
  - - 2013-11-15 19:01:36.926968 Z
    - Caoimhe Chaos <caoimhechaos@protonmail.com>
    - created
    - Enhanced version with Cassandra backend
  - - 2014-09-02 20:52:33.645380 Z
    - Caoimhe Chaos <caoimhechaos@protonmail.com>
    - released
    - Release 0.3 seems to be ready to be set free.
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.4"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2013-11-15 19:01:52.990244 Z
    - Caoimhe Chaos <caoimhechaos@protonmail.com>
    - created
    - Version with e-mail verification codes
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.2.1
  status: :released
  release_time: 2014-06-05 01:53:55.047815 Z
  log_events: 
  - - 2014-02-09 05:19:53.993010 Z
    - Caoimhe Chaos <caoimhechaos@protonmail.com>
    - created
    - First patch release of version 0.2.
  - - 2014-06-05 01:53:55.047825 Z
    - Caoimhe Chaos <caoimhechaos@protonmail.com>
    - released
    - ""
