FROM fedora:28
LABEL maintainer Tonnerre LOMBARD <tonnerre@ancient-solutions.com>

COPY membersys /go/bin/membersys

RUN ["/usr/sbin/adduser", "--system", "--home", "/nonexistent", "--no-create-home", "--comment", "Starship Factory Membership Management System", "--user-group", "sf-membersys"]
VOLUME ["/etc/membersys", "/tls", "/var/www/templates"]
USER sf-membersys
ENTRYPOINT ["/go/bin/membersys"]
CMD ["--config=/etc/membersys/membersys.conf"]
